//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGTGetBills")]
public interface IGTGetBills
{
    
    // CODEGEN: Parameter 'GetBillOfEntryDetailsForFZAResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForFZA", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForFZAResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetBillOfEntryDetailsForFZAResponse GetBillOfEntryDetailsForFZA(GetBillOfEntryDetailsForFZARequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForFZA", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForFZAResponse")]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsForFZAResponse> GetBillOfEntryDetailsForFZAAsync(GetBillOfEntryDetailsForFZARequest request);
    
    // CODEGEN: Parameter 'GetBillOfEntryDetailsForPortResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForPort", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForPortResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetBillOfEntryDetailsForPortResponse GetBillOfEntryDetailsForPort(GetBillOfEntryDetailsForPortRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForPort", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsForPortResponse")]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsForPortResponse> GetBillOfEntryDetailsForPortAsync(GetBillOfEntryDetailsForPortRequest request);
    
    // CODEGEN: Parameter 'GetBillOfEntryDetailsByBarcodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsByBarcode", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsByBarcodeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetBillOfEntryDetailsByBarcodeResponse GetBillOfEntryDetailsByBarcode(GetBillOfEntryDetailsByBarcodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsByBarcode", ReplyAction="http://tempuri.org/IGTGetBills/GetBillOfEntryDetailsByBarcodeResponse")]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsByBarcodeResponse> GetBillOfEntryDetailsByBarcodeAsync(GetBillOfEntryDetailsByBarcodeRequest request);
    
    // CODEGEN: Parameter 'GetCompositeBOEByBarcodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetCompositeBOEByBarcode", ReplyAction="http://tempuri.org/IGTGetBills/GetCompositeBOEByBarcodeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetCompositeBOEByBarcodeResponse GetCompositeBOEByBarcode(GetCompositeBOEByBarcodeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/GetCompositeBOEByBarcode", ReplyAction="http://tempuri.org/IGTGetBills/GetCompositeBOEByBarcodeResponse")]
    System.Threading.Tasks.Task<GetCompositeBOEByBarcodeResponse> GetCompositeBOEByBarcodeAsync(GetCompositeBOEByBarcodeRequest request);
    
    // CODEGEN: Parameter 'ContainerInfoGT2ShjCustResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/ContainerInfoGT2ShjCust", ReplyAction="http://tempuri.org/IGTGetBills/ContainerInfoGT2ShjCustResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ContainerInfoGT2ShjCustResponse ContainerInfoGT2ShjCust(ContainerInfoGT2ShjCustRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGTGetBills/ContainerInfoGT2ShjCust", ReplyAction="http://tempuri.org/IGTGetBills/ContainerInfoGT2ShjCustResponse")]
    System.Threading.Tasks.Task<ContainerInfoGT2ShjCustResponse> ContainerInfoGT2ShjCustAsync(ContainerInfoGT2ShjCustRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsForFZA", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsForFZARequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int b_year;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string b_section;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string b_billno;
    
    public GetBillOfEntryDetailsForFZARequest()
    {
    }
    
    public GetBillOfEntryDetailsForFZARequest(int b_year, string b_section, string b_billno)
    {
        this.b_year = b_year;
        this.b_section = b_section;
        this.b_billno = b_billno;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsForFZAResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsForFZAResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet GetBillOfEntryDetailsForFZAResult;
    
    public GetBillOfEntryDetailsForFZAResponse()
    {
    }
    
    public GetBillOfEntryDetailsForFZAResponse(System.Data.DataSet GetBillOfEntryDetailsForFZAResult)
    {
        this.GetBillOfEntryDetailsForFZAResult = GetBillOfEntryDetailsForFZAResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsForPort", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsForPortRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int b_year;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string b_section;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string b_bill_type;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string b_billno;
    
    public GetBillOfEntryDetailsForPortRequest()
    {
    }
    
    public GetBillOfEntryDetailsForPortRequest(int b_year, string b_section, string b_bill_type, string b_billno)
    {
        this.b_year = b_year;
        this.b_section = b_section;
        this.b_bill_type = b_bill_type;
        this.b_billno = b_billno;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsForPortResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsForPortResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet GetBillOfEntryDetailsForPortResult;
    
    public GetBillOfEntryDetailsForPortResponse()
    {
    }
    
    public GetBillOfEntryDetailsForPortResponse(System.Data.DataSet GetBillOfEntryDetailsForPortResult)
    {
        this.GetBillOfEntryDetailsForPortResult = GetBillOfEntryDetailsForPortResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsByBarcode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsByBarcodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BarcodeValue;
    
    public GetBillOfEntryDetailsByBarcodeRequest()
    {
    }
    
    public GetBillOfEntryDetailsByBarcodeRequest(string BarcodeValue)
    {
        this.BarcodeValue = BarcodeValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetBillOfEntryDetailsByBarcodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetBillOfEntryDetailsByBarcodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet GetBillOfEntryDetailsByBarcodeResult;
    
    public GetBillOfEntryDetailsByBarcodeResponse()
    {
    }
    
    public GetBillOfEntryDetailsByBarcodeResponse(System.Data.DataSet GetBillOfEntryDetailsByBarcodeResult)
    {
        this.GetBillOfEntryDetailsByBarcodeResult = GetBillOfEntryDetailsByBarcodeResult;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GetBillInfo")]
public partial class GetDetails
{
    
    private System.Data.DataSet datasetValueField;
    
    private int errorNoField;
    
    private bool errorNoFieldSpecified;
    
    private string errMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Data.DataSet DatasetValue
    {
        get
        {
            return this.datasetValueField;
        }
        set
        {
            this.datasetValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int ErrorNo
    {
        get
        {
            return this.errorNoField;
        }
        set
        {
            this.errorNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorNoSpecified
    {
        get
        {
            return this.errorNoFieldSpecified;
        }
        set
        {
            this.errorNoFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string errMessage
    {
        get
        {
            return this.errMessageField;
        }
        set
        {
            this.errMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GetBillInfo")]
public partial class RootOut
{
    
    private string remarksField;
    
    private string requestNoField;
    
    private string statusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string Remarks
    {
        get
        {
            return this.remarksField;
        }
        set
        {
            this.remarksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string RequestNo
    {
        get
        {
            return this.requestNoField;
        }
        set
        {
            this.requestNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GetBillInfo")]
public partial class RootIn
{
    
    private System.Data.DataSet datasetValueField;
    
    private string remarksField;
    
    private System.DateTime requestDateField;
    
    private bool requestDateFieldSpecified;
    
    private string requestNoField;
    
    private int statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Data.DataSet DatasetValue
    {
        get
        {
            return this.datasetValueField;
        }
        set
        {
            this.datasetValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Remarks
    {
        get
        {
            return this.remarksField;
        }
        set
        {
            this.remarksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime RequestDate
    {
        get
        {
            return this.requestDateField;
        }
        set
        {
            this.requestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequestDateSpecified
    {
        get
        {
            return this.requestDateFieldSpecified;
        }
        set
        {
            this.requestDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string RequestNo
    {
        get
        {
            return this.requestNoField;
        }
        set
        {
            this.requestNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified
    {
        get
        {
            return this.statusFieldSpecified;
        }
        set
        {
            this.statusFieldSpecified = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositeBOEByBarcode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCompositeBOEByBarcodeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BarcodeValue;
    
    public GetCompositeBOEByBarcodeRequest()
    {
    }
    
    public GetCompositeBOEByBarcodeRequest(string BarcodeValue)
    {
        this.BarcodeValue = BarcodeValue;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetCompositeBOEByBarcodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetCompositeBOEByBarcodeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetDetails GetCompositeBOEByBarcodeResult;
    
    public GetCompositeBOEByBarcodeResponse()
    {
    }
    
    public GetCompositeBOEByBarcodeResponse(GetDetails GetCompositeBOEByBarcodeResult)
    {
        this.GetCompositeBOEByBarcodeResult = GetCompositeBOEByBarcodeResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ContainerInfoGT2ShjCust", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ContainerInfoGT2ShjCustRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public RootIn InputValues;
    
    public ContainerInfoGT2ShjCustRequest()
    {
    }
    
    public ContainerInfoGT2ShjCustRequest(RootIn InputValues)
    {
        this.InputValues = InputValues;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ContainerInfoGT2ShjCustResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ContainerInfoGT2ShjCustResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public RootOut ContainerInfoGT2ShjCustResult;
    
    public ContainerInfoGT2ShjCustResponse()
    {
    }
    
    public ContainerInfoGT2ShjCustResponse(RootOut ContainerInfoGT2ShjCustResult)
    {
        this.ContainerInfoGT2ShjCustResult = ContainerInfoGT2ShjCustResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGTGetBillsChannel : IGTGetBills, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GTGetBillsClient : System.ServiceModel.ClientBase<IGTGetBills>, IGTGetBills
{
    
    public GTGetBillsClient()
    {
    }
    
    public GTGetBillsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GTGetBillsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GTGetBillsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GTGetBillsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBillOfEntryDetailsForFZAResponse IGTGetBills.GetBillOfEntryDetailsForFZA(GetBillOfEntryDetailsForFZARequest request)
    {
        return base.Channel.GetBillOfEntryDetailsForFZA(request);
    }
    
    public System.Data.DataSet GetBillOfEntryDetailsForFZA(int b_year, string b_section, string b_billno)
    {
        GetBillOfEntryDetailsForFZARequest inValue = new GetBillOfEntryDetailsForFZARequest();
        inValue.b_year = b_year;
        inValue.b_section = b_section;
        inValue.b_billno = b_billno;
        GetBillOfEntryDetailsForFZAResponse retVal = ((IGTGetBills)(this)).GetBillOfEntryDetailsForFZA(inValue);
        return retVal.GetBillOfEntryDetailsForFZAResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsForFZAResponse> IGTGetBills.GetBillOfEntryDetailsForFZAAsync(GetBillOfEntryDetailsForFZARequest request)
    {
        return base.Channel.GetBillOfEntryDetailsForFZAAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetBillOfEntryDetailsForFZAResponse> GetBillOfEntryDetailsForFZAAsync(int b_year, string b_section, string b_billno)
    {
        GetBillOfEntryDetailsForFZARequest inValue = new GetBillOfEntryDetailsForFZARequest();
        inValue.b_year = b_year;
        inValue.b_section = b_section;
        inValue.b_billno = b_billno;
        return ((IGTGetBills)(this)).GetBillOfEntryDetailsForFZAAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBillOfEntryDetailsForPortResponse IGTGetBills.GetBillOfEntryDetailsForPort(GetBillOfEntryDetailsForPortRequest request)
    {
        return base.Channel.GetBillOfEntryDetailsForPort(request);
    }
    
    public System.Data.DataSet GetBillOfEntryDetailsForPort(int b_year, string b_section, string b_bill_type, string b_billno)
    {
        GetBillOfEntryDetailsForPortRequest inValue = new GetBillOfEntryDetailsForPortRequest();
        inValue.b_year = b_year;
        inValue.b_section = b_section;
        inValue.b_bill_type = b_bill_type;
        inValue.b_billno = b_billno;
        GetBillOfEntryDetailsForPortResponse retVal = ((IGTGetBills)(this)).GetBillOfEntryDetailsForPort(inValue);
        return retVal.GetBillOfEntryDetailsForPortResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsForPortResponse> IGTGetBills.GetBillOfEntryDetailsForPortAsync(GetBillOfEntryDetailsForPortRequest request)
    {
        return base.Channel.GetBillOfEntryDetailsForPortAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetBillOfEntryDetailsForPortResponse> GetBillOfEntryDetailsForPortAsync(int b_year, string b_section, string b_bill_type, string b_billno)
    {
        GetBillOfEntryDetailsForPortRequest inValue = new GetBillOfEntryDetailsForPortRequest();
        inValue.b_year = b_year;
        inValue.b_section = b_section;
        inValue.b_bill_type = b_bill_type;
        inValue.b_billno = b_billno;
        return ((IGTGetBills)(this)).GetBillOfEntryDetailsForPortAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetBillOfEntryDetailsByBarcodeResponse IGTGetBills.GetBillOfEntryDetailsByBarcode(GetBillOfEntryDetailsByBarcodeRequest request)
    {
        return base.Channel.GetBillOfEntryDetailsByBarcode(request);
    }
    
    public System.Data.DataSet GetBillOfEntryDetailsByBarcode(string BarcodeValue)
    {
        GetBillOfEntryDetailsByBarcodeRequest inValue = new GetBillOfEntryDetailsByBarcodeRequest();
        inValue.BarcodeValue = BarcodeValue;
        GetBillOfEntryDetailsByBarcodeResponse retVal = ((IGTGetBills)(this)).GetBillOfEntryDetailsByBarcode(inValue);
        return retVal.GetBillOfEntryDetailsByBarcodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetBillOfEntryDetailsByBarcodeResponse> IGTGetBills.GetBillOfEntryDetailsByBarcodeAsync(GetBillOfEntryDetailsByBarcodeRequest request)
    {
        return base.Channel.GetBillOfEntryDetailsByBarcodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetBillOfEntryDetailsByBarcodeResponse> GetBillOfEntryDetailsByBarcodeAsync(string BarcodeValue)
    {
        GetBillOfEntryDetailsByBarcodeRequest inValue = new GetBillOfEntryDetailsByBarcodeRequest();
        inValue.BarcodeValue = BarcodeValue;
        return ((IGTGetBills)(this)).GetBillOfEntryDetailsByBarcodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetCompositeBOEByBarcodeResponse IGTGetBills.GetCompositeBOEByBarcode(GetCompositeBOEByBarcodeRequest request)
    {
        return base.Channel.GetCompositeBOEByBarcode(request);
    }
    
    public GetDetails GetCompositeBOEByBarcode(string BarcodeValue)
    {
        GetCompositeBOEByBarcodeRequest inValue = new GetCompositeBOEByBarcodeRequest();
        inValue.BarcodeValue = BarcodeValue;
        GetCompositeBOEByBarcodeResponse retVal = ((IGTGetBills)(this)).GetCompositeBOEByBarcode(inValue);
        return retVal.GetCompositeBOEByBarcodeResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetCompositeBOEByBarcodeResponse> IGTGetBills.GetCompositeBOEByBarcodeAsync(GetCompositeBOEByBarcodeRequest request)
    {
        return base.Channel.GetCompositeBOEByBarcodeAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetCompositeBOEByBarcodeResponse> GetCompositeBOEByBarcodeAsync(string BarcodeValue)
    {
        GetCompositeBOEByBarcodeRequest inValue = new GetCompositeBOEByBarcodeRequest();
        inValue.BarcodeValue = BarcodeValue;
        return ((IGTGetBills)(this)).GetCompositeBOEByBarcodeAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ContainerInfoGT2ShjCustResponse IGTGetBills.ContainerInfoGT2ShjCust(ContainerInfoGT2ShjCustRequest request)
    {
        return base.Channel.ContainerInfoGT2ShjCust(request);
    }
    
    public RootOut ContainerInfoGT2ShjCust(RootIn InputValues)
    {
        ContainerInfoGT2ShjCustRequest inValue = new ContainerInfoGT2ShjCustRequest();
        inValue.InputValues = InputValues;
        ContainerInfoGT2ShjCustResponse retVal = ((IGTGetBills)(this)).ContainerInfoGT2ShjCust(inValue);
        return retVal.ContainerInfoGT2ShjCustResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ContainerInfoGT2ShjCustResponse> IGTGetBills.ContainerInfoGT2ShjCustAsync(ContainerInfoGT2ShjCustRequest request)
    {
        return base.Channel.ContainerInfoGT2ShjCustAsync(request);
    }
    
    public System.Threading.Tasks.Task<ContainerInfoGT2ShjCustResponse> ContainerInfoGT2ShjCustAsync(RootIn InputValues)
    {
        ContainerInfoGT2ShjCustRequest inValue = new ContainerInfoGT2ShjCustRequest();
        inValue.InputValues = InputValues;
        return ((IGTGetBills)(this)).ContainerInfoGT2ShjCustAsync(inValue);
    }
}
