//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceCIMPMessageGenerationSoap")]
public interface WebServiceCIMPMessageGenerationSoap
{
    
    // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
    HelloWorldResponse HelloWorld(HelloWorldRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
    System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync(HelloWorldRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateMessage", ReplyAction="*")]
    GenerateMessageResponse GenerateMessage(GenerateMessageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateMessage", ReplyAction="*")]
    System.Threading.Tasks.Task<GenerateMessageResponse> GenerateMessageAsync(GenerateMessageRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
    SendEmailResponse SendEmail(SendEmailRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
    System.Threading.Tasks.Task<SendEmailResponse> SendEmailAsync(SendEmailRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HelloWorldRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
    public HelloWorldRequestBody Body;
    
    public HelloWorldRequest()
    {
    }
    
    public HelloWorldRequest(HelloWorldRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class HelloWorldRequestBody
{
    
    public HelloWorldRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class HelloWorldResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
    public HelloWorldResponseBody Body;
    
    public HelloWorldResponse()
    {
    }
    
    public HelloWorldResponse(HelloWorldResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class HelloWorldResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string HelloWorldResult;
    
    public HelloWorldResponseBody()
    {
    }
    
    public HelloWorldResponseBody(string HelloWorldResult)
    {
        this.HelloWorldResult = HelloWorldResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GenerateMessageRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMessage", Namespace="http://tempuri.org/", Order=0)]
    public GenerateMessageRequestBody Body;
    
    public GenerateMessageRequest()
    {
    }
    
    public GenerateMessageRequest(GenerateMessageRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GenerateMessageRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string lMsgtype;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string lSerNo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string lOutputType;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
    public bool vSaveMsgInDB;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string lMsgSubtype;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string vReceiver;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
    public string vReceiverType;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
    public string vOutputStructureType;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
    public string vFlightNo;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
    public System.DateTime VFlightDate;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
    public decimal vMsgReqIDToUpdate;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
    public string vOrigin;
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
    public bool vInsertDoubleSig;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
    public string vVersion;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
    public string vNOP;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
    public string vGrossWeight;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
    public string vVolAmount;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
    public string lEventTimeStampStr;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
    public string vMsgSeqNo;
    
    public GenerateMessageRequestBody()
    {
    }
    
    public GenerateMessageRequestBody(
                string lMsgtype, 
                string lSerNo, 
                string lOutputType, 
                bool vSaveMsgInDB, 
                string lMsgSubtype, 
                string vReceiver, 
                string vReceiverType, 
                string vOutputStructureType, 
                string vFlightNo, 
                System.DateTime VFlightDate, 
                decimal vMsgReqIDToUpdate, 
                string vOrigin, 
                bool vInsertDoubleSig, 
                string vVersion, 
                string vNOP, 
                string vGrossWeight, 
                string vVolAmount, 
                string lEventTimeStampStr, 
                string vMsgSeqNo)
    {
        this.lMsgtype = lMsgtype;
        this.lSerNo = lSerNo;
        this.lOutputType = lOutputType;
        this.vSaveMsgInDB = vSaveMsgInDB;
        this.lMsgSubtype = lMsgSubtype;
        this.vReceiver = vReceiver;
        this.vReceiverType = vReceiverType;
        this.vOutputStructureType = vOutputStructureType;
        this.vFlightNo = vFlightNo;
        this.VFlightDate = VFlightDate;
        this.vMsgReqIDToUpdate = vMsgReqIDToUpdate;
        this.vOrigin = vOrigin;
        this.vInsertDoubleSig = vInsertDoubleSig;
        this.vVersion = vVersion;
        this.vNOP = vNOP;
        this.vGrossWeight = vGrossWeight;
        this.vVolAmount = vVolAmount;
        this.lEventTimeStampStr = lEventTimeStampStr;
        this.vMsgSeqNo = vMsgSeqNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GenerateMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMessageResponse", Namespace="http://tempuri.org/", Order=0)]
    public GenerateMessageResponseBody Body;
    
    public GenerateMessageResponse()
    {
    }
    
    public GenerateMessageResponse(GenerateMessageResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class GenerateMessageResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string GenerateMessageResult;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string vNOP;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string vGrossWeight;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string vVolAmount;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string lEventTimeStampStr;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string vMsgSeqNo;
    
    public GenerateMessageResponseBody()
    {
    }
    
    public GenerateMessageResponseBody(string GenerateMessageResult, string vNOP, string vGrossWeight, string vVolAmount, string lEventTimeStampStr, string vMsgSeqNo)
    {
        this.GenerateMessageResult = GenerateMessageResult;
        this.vNOP = vNOP;
        this.vGrossWeight = vGrossWeight;
        this.vVolAmount = vVolAmount;
        this.lEventTimeStampStr = lEventTimeStampStr;
        this.vMsgSeqNo = vMsgSeqNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendEmailRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
    public SendEmailRequestBody Body;
    
    public SendEmailRequest()
    {
    }
    
    public SendEmailRequest(SendEmailRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class SendEmailRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string lMsgtype;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string lSerNo;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string lOutputText;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string lEMailText;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
    public string lSITA;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
    public string lblStatus;
    
    public SendEmailRequestBody()
    {
    }
    
    public SendEmailRequestBody(string lMsgtype, string lSerNo, string lOutputText, string lEMailText, string lSITA, string lblStatus)
    {
        this.lMsgtype = lMsgtype;
        this.lSerNo = lSerNo;
        this.lOutputText = lOutputText;
        this.lEMailText = lEMailText;
        this.lSITA = lSITA;
        this.lblStatus = lblStatus;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SendEmailResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
    public SendEmailResponseBody Body;
    
    public SendEmailResponse()
    {
    }
    
    public SendEmailResponse(SendEmailResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class SendEmailResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public object SendEmailResult;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string lblStatus;
    
    public SendEmailResponseBody()
    {
    }
    
    public SendEmailResponseBody(object SendEmailResult, string lblStatus)
    {
        this.SendEmailResult = SendEmailResult;
        this.lblStatus = lblStatus;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface WebServiceCIMPMessageGenerationSoapChannel : WebServiceCIMPMessageGenerationSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebServiceCIMPMessageGenerationSoapClient : System.ServiceModel.ClientBase<WebServiceCIMPMessageGenerationSoap>, WebServiceCIMPMessageGenerationSoap
{
    
    public WebServiceCIMPMessageGenerationSoapClient()
    {
    }
    
    public WebServiceCIMPMessageGenerationSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebServiceCIMPMessageGenerationSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceCIMPMessageGenerationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebServiceCIMPMessageGenerationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    HelloWorldResponse WebServiceCIMPMessageGenerationSoap.HelloWorld(HelloWorldRequest request)
    {
        return base.Channel.HelloWorld(request);
    }
    
    public string HelloWorld()
    {
        HelloWorldRequest inValue = new HelloWorldRequest();
        inValue.Body = new HelloWorldRequestBody();
        HelloWorldResponse retVal = ((WebServiceCIMPMessageGenerationSoap)(this)).HelloWorld(inValue);
        return retVal.Body.HelloWorldResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<HelloWorldResponse> WebServiceCIMPMessageGenerationSoap.HelloWorldAsync(HelloWorldRequest request)
    {
        return base.Channel.HelloWorldAsync(request);
    }
    
    public System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync()
    {
        HelloWorldRequest inValue = new HelloWorldRequest();
        inValue.Body = new HelloWorldRequestBody();
        return ((WebServiceCIMPMessageGenerationSoap)(this)).HelloWorldAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GenerateMessageResponse WebServiceCIMPMessageGenerationSoap.GenerateMessage(GenerateMessageRequest request)
    {
        return base.Channel.GenerateMessage(request);
    }
    
    public string GenerateMessage(
                string lMsgtype, 
                string lSerNo, 
                string lOutputType, 
                bool vSaveMsgInDB, 
                string lMsgSubtype, 
                string vReceiver, 
                string vReceiverType, 
                string vOutputStructureType, 
                string vFlightNo, 
                System.DateTime VFlightDate, 
                decimal vMsgReqIDToUpdate, 
                string vOrigin, 
                bool vInsertDoubleSig, 
                string vVersion, 
                ref string vNOP, 
                ref string vGrossWeight, 
                ref string vVolAmount, 
                ref string lEventTimeStampStr, 
                ref string vMsgSeqNo)
    {
        GenerateMessageRequest inValue = new GenerateMessageRequest();
        inValue.Body = new GenerateMessageRequestBody();
        inValue.Body.lMsgtype = lMsgtype;
        inValue.Body.lSerNo = lSerNo;
        inValue.Body.lOutputType = lOutputType;
        inValue.Body.vSaveMsgInDB = vSaveMsgInDB;
        inValue.Body.lMsgSubtype = lMsgSubtype;
        inValue.Body.vReceiver = vReceiver;
        inValue.Body.vReceiverType = vReceiverType;
        inValue.Body.vOutputStructureType = vOutputStructureType;
        inValue.Body.vFlightNo = vFlightNo;
        inValue.Body.VFlightDate = VFlightDate;
        inValue.Body.vMsgReqIDToUpdate = vMsgReqIDToUpdate;
        inValue.Body.vOrigin = vOrigin;
        inValue.Body.vInsertDoubleSig = vInsertDoubleSig;
        inValue.Body.vVersion = vVersion;
        inValue.Body.vNOP = vNOP;
        inValue.Body.vGrossWeight = vGrossWeight;
        inValue.Body.vVolAmount = vVolAmount;
        inValue.Body.lEventTimeStampStr = lEventTimeStampStr;
        inValue.Body.vMsgSeqNo = vMsgSeqNo;
        GenerateMessageResponse retVal = ((WebServiceCIMPMessageGenerationSoap)(this)).GenerateMessage(inValue);
        vNOP = retVal.Body.vNOP;
        vGrossWeight = retVal.Body.vGrossWeight;
        vVolAmount = retVal.Body.vVolAmount;
        lEventTimeStampStr = retVal.Body.lEventTimeStampStr;
        vMsgSeqNo = retVal.Body.vMsgSeqNo;
        return retVal.Body.GenerateMessageResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GenerateMessageResponse> WebServiceCIMPMessageGenerationSoap.GenerateMessageAsync(GenerateMessageRequest request)
    {
        return base.Channel.GenerateMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<GenerateMessageResponse> GenerateMessageAsync(
                string lMsgtype, 
                string lSerNo, 
                string lOutputType, 
                bool vSaveMsgInDB, 
                string lMsgSubtype, 
                string vReceiver, 
                string vReceiverType, 
                string vOutputStructureType, 
                string vFlightNo, 
                System.DateTime VFlightDate, 
                decimal vMsgReqIDToUpdate, 
                string vOrigin, 
                bool vInsertDoubleSig, 
                string vVersion, 
                string vNOP, 
                string vGrossWeight, 
                string vVolAmount, 
                string lEventTimeStampStr, 
                string vMsgSeqNo)
    {
        GenerateMessageRequest inValue = new GenerateMessageRequest();
        inValue.Body = new GenerateMessageRequestBody();
        inValue.Body.lMsgtype = lMsgtype;
        inValue.Body.lSerNo = lSerNo;
        inValue.Body.lOutputType = lOutputType;
        inValue.Body.vSaveMsgInDB = vSaveMsgInDB;
        inValue.Body.lMsgSubtype = lMsgSubtype;
        inValue.Body.vReceiver = vReceiver;
        inValue.Body.vReceiverType = vReceiverType;
        inValue.Body.vOutputStructureType = vOutputStructureType;
        inValue.Body.vFlightNo = vFlightNo;
        inValue.Body.VFlightDate = VFlightDate;
        inValue.Body.vMsgReqIDToUpdate = vMsgReqIDToUpdate;
        inValue.Body.vOrigin = vOrigin;
        inValue.Body.vInsertDoubleSig = vInsertDoubleSig;
        inValue.Body.vVersion = vVersion;
        inValue.Body.vNOP = vNOP;
        inValue.Body.vGrossWeight = vGrossWeight;
        inValue.Body.vVolAmount = vVolAmount;
        inValue.Body.lEventTimeStampStr = lEventTimeStampStr;
        inValue.Body.vMsgSeqNo = vMsgSeqNo;
        return ((WebServiceCIMPMessageGenerationSoap)(this)).GenerateMessageAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendEmailResponse WebServiceCIMPMessageGenerationSoap.SendEmail(SendEmailRequest request)
    {
        return base.Channel.SendEmail(request);
    }
    
    public object SendEmail(string lMsgtype, string lSerNo, string lOutputText, string lEMailText, string lSITA, ref string lblStatus)
    {
        SendEmailRequest inValue = new SendEmailRequest();
        inValue.Body = new SendEmailRequestBody();
        inValue.Body.lMsgtype = lMsgtype;
        inValue.Body.lSerNo = lSerNo;
        inValue.Body.lOutputText = lOutputText;
        inValue.Body.lEMailText = lEMailText;
        inValue.Body.lSITA = lSITA;
        inValue.Body.lblStatus = lblStatus;
        SendEmailResponse retVal = ((WebServiceCIMPMessageGenerationSoap)(this)).SendEmail(inValue);
        lblStatus = retVal.Body.lblStatus;
        return retVal.Body.SendEmailResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendEmailResponse> WebServiceCIMPMessageGenerationSoap.SendEmailAsync(SendEmailRequest request)
    {
        return base.Channel.SendEmailAsync(request);
    }
    
    public System.Threading.Tasks.Task<SendEmailResponse> SendEmailAsync(string lMsgtype, string lSerNo, string lOutputText, string lEMailText, string lSITA, string lblStatus)
    {
        SendEmailRequest inValue = new SendEmailRequest();
        inValue.Body = new SendEmailRequestBody();
        inValue.Body.lMsgtype = lMsgtype;
        inValue.Body.lSerNo = lSerNo;
        inValue.Body.lOutputText = lOutputText;
        inValue.Body.lEMailText = lEMailText;
        inValue.Body.lSITA = lSITA;
        inValue.Body.lblStatus = lblStatus;
        return ((WebServiceCIMPMessageGenerationSoap)(this)).SendEmailAsync(inValue);
    }
}
