//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace CargoFlash.Cargo.DataService.Common
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    using System.Configuration;
    using System.ServiceModel.Configuration;
    using System.ServiceModel.Web;
    using System.Net;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WebServiceEDIMSGValidateAndReturnDSSoap", Namespace = "http://tempuri.org/")]
    public partial class WebServiceEDIMSGValidateAndReturnDS : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback ValidateMSGJQueryOperationCompleted;

        private System.Threading.SendOrPostCallback ValidateMSGAndReturnDataSetOperationCompleted;

        /// <remarks/>
        public WebServiceEDIMSGValidateAndReturnDS()
        {
            //this.Url = "http://52.187.30.105/edi/PresentationLayer/WebServiceEDIMSGValidateAndReturnDS.as" +
            //    "mx";
            try
            {
                ClientSection clientSection = ConfigurationManager.GetSection("system.serviceModel/client") as ClientSection;
                ChannelEndpointElementCollection endpointCollection =
                clientSection.ElementInformation.Properties[string.Empty].Value as ChannelEndpointElementCollection;
                string URl = "";
                foreach (ChannelEndpointElement endpointElement in endpointCollection)
                {
                    if (endpointElement.Name == "WebServiceEDIMSGValidateAndReturnDSSoap")
                    {
                        URl = endpointElement.Address.AbsoluteUri;
                    }
                }
                this.Url = "" + URl + "";
            }
            catch (Exception ex)//(Exception ex)
            {
                throw ex;
            }
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event ValidateMSGJQueryCompletedEventHandler ValidateMSGJQueryCompleted;

        /// <remarks/>
        public event ValidateMSGAndReturnDataSetCompletedEventHandler ValidateMSGAndReturnDataSetCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld()
        {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync()
        {
            this.HelloWorldAsync(null);
        }

        /// <remarks/>
        public void HelloWorldAsync(object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateMSGJQuery", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public lstValidateDataRetun ValidateMSGJQuery(string MsgTxt)
        {
            object[] results = this.Invoke("ValidateMSGJQuery", new object[] {
                        MsgTxt});
            return ((lstValidateDataRetun)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginValidateMSGJQuery(string MsgTxt, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ValidateMSGJQuery", new object[] {
                        MsgTxt}, callback, asyncState);
        }

        /// <remarks/>
        public lstValidateDataRetun EndValidateMSGJQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((lstValidateDataRetun)(results[0]));
        }

        /// <remarks/>
        public void ValidateMSGJQueryAsync(string MsgTxt)
        {
            this.ValidateMSGJQueryAsync(MsgTxt, null);
        }

        /// <remarks/>
        public void ValidateMSGJQueryAsync(string MsgTxt, object userState)
        {
            if ((this.ValidateMSGJQueryOperationCompleted == null))
            {
                this.ValidateMSGJQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateMSGJQueryOperationCompleted);
            }
            this.InvokeAsync("ValidateMSGJQuery", new object[] {
                        MsgTxt}, this.ValidateMSGJQueryOperationCompleted, userState);
        }

        private void OnValidateMSGJQueryOperationCompleted(object arg)
        {
            if ((this.ValidateMSGJQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateMSGJQueryCompleted(this, new ValidateMSGJQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateMSGAndReturnDataSet", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ValidateMSGAndReturnDataSet(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo)
        {
            object[] results = this.Invoke("ValidateMSGAndReturnDataSet", new object[] {
                        MsgTxt,
                        MsgRecFrom,
                        MsgRecAddress,
                        PreviousSNo});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginValidateMSGAndReturnDataSet(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ValidateMSGAndReturnDataSet", new object[] {
                        MsgTxt,
                        MsgRecFrom,
                        MsgRecAddress,
                        PreviousSNo}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndValidateMSGAndReturnDataSet(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void ValidateMSGAndReturnDataSetAsync(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo)
        {
            this.ValidateMSGAndReturnDataSetAsync(MsgTxt, MsgRecFrom, MsgRecAddress, PreviousSNo, null);
        }

        /// <remarks/>
        public void ValidateMSGAndReturnDataSetAsync(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo, object userState)
        {
            if ((this.ValidateMSGAndReturnDataSetOperationCompleted == null))
            {
                this.ValidateMSGAndReturnDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateMSGAndReturnDataSetOperationCompleted);
            }
            this.InvokeAsync("ValidateMSGAndReturnDataSet", new object[] {
                        MsgTxt,
                        MsgRecFrom,
                        MsgRecAddress,
                        PreviousSNo}, this.ValidateMSGAndReturnDataSetOperationCompleted, userState);
        }

        private void OnValidateMSGAndReturnDataSetOperationCompleted(object arg)
        {
            if ((this.ValidateMSGAndReturnDataSetCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateMSGAndReturnDataSetCompleted(this, new ValidateMSGAndReturnDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class lstValidateDataRetun
    {

        private clsExecutionResult[] lstClsExecutionResultField;

        private clsMessageData[] lstClsMessageDataField;

        private clsMessageDetails lstClsMessageDetailsField;

        /// <remarks/>
        public clsExecutionResult[] lstClsExecutionResult
        {
            get
            {
                return this.lstClsExecutionResultField;
            }
            set
            {
                this.lstClsExecutionResultField = value;
            }
        }

        /// <remarks/>
        public clsMessageData[] lstClsMessageData
        {
            get
            {
                return this.lstClsMessageDataField;
            }
            set
            {
                this.lstClsMessageDataField = value;
            }
        }

        /// <remarks/>
        public clsMessageDetails lstClsMessageDetails
        {
            get
            {
                return this.lstClsMessageDetailsField;
            }
            set
            {
                this.lstClsMessageDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class clsExecutionResult
    {

        private string idField;

        private string areaField;

        private string returnCodeField;

        private string reasonCodeField;

        private string languageField;

        private string techinicalDescriptionField;

        private string userDescriptionField;

        private string correctiveActionField;

        private string typeField;

        private string severityField;

        private string moduleNameField;

        private string procNameField;

        /// <remarks/>
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Area
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }

        /// <remarks/>
        public string ReasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }

        /// <remarks/>
        public string Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string TechinicalDescription
        {
            get
            {
                return this.techinicalDescriptionField;
            }
            set
            {
                this.techinicalDescriptionField = value;
            }
        }

        /// <remarks/>
        public string UserDescription
        {
            get
            {
                return this.userDescriptionField;
            }
            set
            {
                this.userDescriptionField = value;
            }
        }

        /// <remarks/>
        public string CorrectiveAction
        {
            get
            {
                return this.correctiveActionField;
            }
            set
            {
                this.correctiveActionField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        /// <remarks/>
        public string ModuleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
            }
        }

        /// <remarks/>
        public string ProcName
        {
            get
            {
                return this.procNameField;
            }
            set
            {
                this.procNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class clsMessageDetails
    {

        private string lMessageTypeField;

        private string lMsgSubTypeField;

        private int lMessageVersionField;

        private long lCharaterCountField;

        private long lLinesCountField;

        private string[] lLinesDataField;

        private string[] lCarimpRefIdField;

        /// <remarks/>
        public string lMessageType
        {
            get
            {
                return this.lMessageTypeField;
            }
            set
            {
                this.lMessageTypeField = value;
            }
        }

        /// <remarks/>
        public string lMsgSubType
        {
            get
            {
                return this.lMsgSubTypeField;
            }
            set
            {
                this.lMsgSubTypeField = value;
            }
        }

        /// <remarks/>
        public int lMessageVersion
        {
            get
            {
                return this.lMessageVersionField;
            }
            set
            {
                this.lMessageVersionField = value;
            }
        }

        /// <remarks/>
        public long lCharaterCount
        {
            get
            {
                return this.lCharaterCountField;
            }
            set
            {
                this.lCharaterCountField = value;
            }
        }

        /// <remarks/>
        public long lLinesCount
        {
            get
            {
                return this.lLinesCountField;
            }
            set
            {
                this.lLinesCountField = value;
            }
        }

        /// <remarks/>
        public string[] lLinesData
        {
            get
            {
                return this.lLinesDataField;
            }
            set
            {
                this.lLinesDataField = value;
            }
        }

        /// <remarks/>
        public string[] lCarimpRefId
        {
            get
            {
                return this.lCarimpRefIdField;
            }
            set
            {
                this.lCarimpRefIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class clsMessageData
    {

        private string carImpRefNoField;

        private string messageDefinitionField;

        private string dataFoundTextField;

        private string sucessField;

        private string regexstringField;

        private string sEQNumberField;

        private string carImpAlphaNoField;

        private string lineNumberInMessageField;

        private string dataGroupIdField;

        private string dataElementIdField;

        private string lineIdentifierField;

        private string internalGroupIdField;

        private string isRepeatableField;

        private string repeatCountField;

        private string minRepeatCountField;

        private string nextLineMessagREGEXField;

        private string repeatCarIMPIdField;

        private string seqOfGroupCountWithinElementField;

        private string isGroupMandatoryField;

        private string linesIncludedField;

        private string includedLinesMinCountField;

        private string includedLinesMaxCountField;

        private string includedLineRepeatConditionField;

        private string includedLineMessagREGEXField;

        private string isThisImmediateChildField;

        private string dataFoundField;

        /// <remarks/>
        public string CarImpRefNo
        {
            get
            {
                return this.carImpRefNoField;
            }
            set
            {
                this.carImpRefNoField = value;
            }
        }

        /// <remarks/>
        public string MessageDefinition
        {
            get
            {
                return this.messageDefinitionField;
            }
            set
            {
                this.messageDefinitionField = value;
            }
        }

        /// <remarks/>
        public string DataFoundText
        {
            get
            {
                return this.dataFoundTextField;
            }
            set
            {
                this.dataFoundTextField = value;
            }
        }

        /// <remarks/>
        public string sucess
        {
            get
            {
                return this.sucessField;
            }
            set
            {
                this.sucessField = value;
            }
        }

        /// <remarks/>
        public string Regexstring
        {
            get
            {
                return this.regexstringField;
            }
            set
            {
                this.regexstringField = value;
            }
        }

        /// <remarks/>
        public string SEQNumber
        {
            get
            {
                return this.sEQNumberField;
            }
            set
            {
                this.sEQNumberField = value;
            }
        }

        /// <remarks/>
        public string CarImpAlphaNo
        {
            get
            {
                return this.carImpAlphaNoField;
            }
            set
            {
                this.carImpAlphaNoField = value;
            }
        }

        /// <remarks/>
        public string LineNumberInMessage
        {
            get
            {
                return this.lineNumberInMessageField;
            }
            set
            {
                this.lineNumberInMessageField = value;
            }
        }

        /// <remarks/>
        public string DataGroupId
        {
            get
            {
                return this.dataGroupIdField;
            }
            set
            {
                this.dataGroupIdField = value;
            }
        }

        /// <remarks/>
        public string DataElementId
        {
            get
            {
                return this.dataElementIdField;
            }
            set
            {
                this.dataElementIdField = value;
            }
        }

        /// <remarks/>
        public string LineIdentifier
        {
            get
            {
                return this.lineIdentifierField;
            }
            set
            {
                this.lineIdentifierField = value;
            }
        }

        /// <remarks/>
        public string InternalGroupId
        {
            get
            {
                return this.internalGroupIdField;
            }
            set
            {
                this.internalGroupIdField = value;
            }
        }

        /// <remarks/>
        public string IsRepeatable
        {
            get
            {
                return this.isRepeatableField;
            }
            set
            {
                this.isRepeatableField = value;
            }
        }

        /// <remarks/>
        public string RepeatCount
        {
            get
            {
                return this.repeatCountField;
            }
            set
            {
                this.repeatCountField = value;
            }
        }

        /// <remarks/>
        public string MinRepeatCount
        {
            get
            {
                return this.minRepeatCountField;
            }
            set
            {
                this.minRepeatCountField = value;
            }
        }

        /// <remarks/>
        public string NextLineMessagREGEX
        {
            get
            {
                return this.nextLineMessagREGEXField;
            }
            set
            {
                this.nextLineMessagREGEXField = value;
            }
        }

        /// <remarks/>
        public string RepeatCarIMPId
        {
            get
            {
                return this.repeatCarIMPIdField;
            }
            set
            {
                this.repeatCarIMPIdField = value;
            }
        }

        /// <remarks/>
        public string SeqOfGroupCountWithinElement
        {
            get
            {
                return this.seqOfGroupCountWithinElementField;
            }
            set
            {
                this.seqOfGroupCountWithinElementField = value;
            }
        }

        /// <remarks/>
        public string IsGroupMandatory
        {
            get
            {
                return this.isGroupMandatoryField;
            }
            set
            {
                this.isGroupMandatoryField = value;
            }
        }

        /// <remarks/>
        public string LinesIncluded
        {
            get
            {
                return this.linesIncludedField;
            }
            set
            {
                this.linesIncludedField = value;
            }
        }

        /// <remarks/>
        public string IncludedLinesMinCount
        {
            get
            {
                return this.includedLinesMinCountField;
            }
            set
            {
                this.includedLinesMinCountField = value;
            }
        }

        /// <remarks/>
        public string IncludedLinesMaxCount
        {
            get
            {
                return this.includedLinesMaxCountField;
            }
            set
            {
                this.includedLinesMaxCountField = value;
            }
        }

        /// <remarks/>
        public string IncludedLineRepeatCondition
        {
            get
            {
                return this.includedLineRepeatConditionField;
            }
            set
            {
                this.includedLineRepeatConditionField = value;
            }
        }

        /// <remarks/>
        public string IncludedLineMessagREGEX
        {
            get
            {
                return this.includedLineMessagREGEXField;
            }
            set
            {
                this.includedLineMessagREGEXField = value;
            }
        }

        /// <remarks/>
        public string IsThisImmediateChild
        {
            get
            {
                return this.isThisImmediateChildField;
            }
            set
            {
                this.isThisImmediateChildField = value;
            }
        }

        /// <remarks/>
        public string DataFound
        {
            get
            {
                return this.dataFoundField;
            }
            set
            {
                this.dataFoundField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ValidateMSGJQueryCompletedEventHandler(object sender, ValidateMSGJQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateMSGJQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ValidateMSGJQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public lstValidateDataRetun Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((lstValidateDataRetun)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void ValidateMSGAndReturnDataSetCompletedEventHandler(object sender, ValidateMSGAndReturnDataSetCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateMSGAndReturnDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ValidateMSGAndReturnDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}
