//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoFlashCargoWebApps.ValidateAndInsertMessage {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidateAndInsertMessage.WebServiceEDIMSGValidateAndReturnDSSoap")]
    public interface WebServiceEDIMSGValidateAndReturnDSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateMSGAndReturnDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ValidateMSGAndReturnDataSet(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateMSGAndReturnDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ValidateMSGAndReturnDataSetAsync(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEDIMSGValidateAndReturnDSSoapChannel : CargoFlashCargoWebApps.ValidateAndInsertMessage.WebServiceEDIMSGValidateAndReturnDSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEDIMSGValidateAndReturnDSSoapClient : System.ServiceModel.ClientBase<CargoFlashCargoWebApps.ValidateAndInsertMessage.WebServiceEDIMSGValidateAndReturnDSSoap>, CargoFlashCargoWebApps.ValidateAndInsertMessage.WebServiceEDIMSGValidateAndReturnDSSoap {
        
        public WebServiceEDIMSGValidateAndReturnDSSoapClient() {
        }
        
        public WebServiceEDIMSGValidateAndReturnDSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEDIMSGValidateAndReturnDSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEDIMSGValidateAndReturnDSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEDIMSGValidateAndReturnDSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet ValidateMSGAndReturnDataSet(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo) {
            return base.Channel.ValidateMSGAndReturnDataSet(MsgTxt, MsgRecFrom, MsgRecAddress, PreviousSNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ValidateMSGAndReturnDataSetAsync(string MsgTxt, string MsgRecFrom, string MsgRecAddress, int PreviousSNo) {
            return base.Channel.ValidateMSGAndReturnDataSetAsync(MsgTxt, MsgRecFrom, MsgRecAddress, PreviousSNo);
        }
    }
}
