//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoFlash.Cargo.DataService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gares.bookmycargo.net/edi/PresentationLayer/Admin/Account/Public/WebServic" +
            "eValidateMsg.asmx")]
        public string CargoFlash_Cargo_DataService_ValidateEDIMsg_WebServiceValidateMsg {
            get {
                return ((string)(this["CargoFlash_Cargo_DataService_ValidateEDIMsg_WebServiceValidateMsg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gares.bookmycargo.net/edi/PresentationLayer/Admin/Account/Public/WebServic" +
            "eValidateMsg.asmx")]
        public string CargoFlash_Cargo_DataService_ValidateEdiMsg1_WebServiceValidateMsg {
            get {
                return ((string)(this["CargoFlash_Cargo_DataService_ValidateEdiMsg1_WebServiceValidateMsg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gares.bookmycargo.net/edi/PresentationLayer/Admin/Account/Public/WebServic" +
            "eValidateMsg.asmx")]
        public string CargoFlash_Cargo_DataService_ValidateEDIMessage_WebServiceValidateMsg {
            get {
                return ((string)(this["CargoFlash_Cargo_DataService_ValidateEDIMessage_WebServiceValidateMsg"]));
            }
        }
    }
}
